// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: g2diagnostic.proto

package com.senzing.g2.engine.grpc.G2Diagnostic;

public interface CheckDBPerfRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:g2diagnostic.CheckDBPerfRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 secondsToRun = 1;</code>
   * @return The secondsToRun.
   */
  int getSecondsToRun();
}
