// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: g2diagnostic.proto

package com.senzing.g2.engine.grpc.G2Diagnostic;

public final class G2DiagnosticProto {
  private G2DiagnosticProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_CheckDBPerfRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_CheckDBPerfRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_CheckDBPerfResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_CheckDBPerfResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_ClearLastExceptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_ClearLastExceptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_ClearLastExceptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_ClearLastExceptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_CloseEntityListBySizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_CloseEntityListBySizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_CloseEntityListBySizeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_CloseEntityListBySizeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_DestroyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_DestroyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_DestroyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_DestroyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_FetchNextEntityBySizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_FetchNextEntityBySizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_FetchNextEntityBySizeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_FetchNextEntityBySizeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_FindEntitiesByFeatureIDsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_FindEntitiesByFeatureIDsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_FindEntitiesByFeatureIDsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_FindEntitiesByFeatureIDsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetAvailableMemoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetAvailableMemoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetAvailableMemoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetAvailableMemoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetDataSourceCountsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetDataSourceCountsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetDataSourceCountsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetDataSourceCountsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetDBInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetDBInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetDBInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetDBInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetEntityDetailsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetEntityDetailsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetEntityDetailsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetEntityDetailsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetEntityListBySizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetEntityListBySizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetEntityListBySizeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetEntityListBySizeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetEntityResumeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetEntityResumeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetEntityResumeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetEntityResumeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetEntitySizeBreakdownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetEntitySizeBreakdownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetEntitySizeBreakdownResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetEntitySizeBreakdownResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetFeatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetFeatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetFeatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetFeatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetGenericFeaturesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetGenericFeaturesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetGenericFeaturesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetGenericFeaturesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetLastExceptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetLastExceptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetLastExceptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetLastExceptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetLastExceptionCodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetLastExceptionCodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetLastExceptionCodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetLastExceptionCodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetLogicalCoresRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetLogicalCoresRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetLogicalCoresResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetLogicalCoresResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetMappingStatisticsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetMappingStatisticsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetMappingStatisticsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetMappingStatisticsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetPhysicalCoresRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetPhysicalCoresRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetPhysicalCoresResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetPhysicalCoresResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetRelationshipDetailsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetRelationshipDetailsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetRelationshipDetailsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetRelationshipDetailsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetResolutionStatisticsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetResolutionStatisticsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetResolutionStatisticsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetResolutionStatisticsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetTotalSystemMemoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetTotalSystemMemoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_GetTotalSystemMemoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_GetTotalSystemMemoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_InitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_InitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_InitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_InitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_InitWithConfigIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_InitWithConfigIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_InitWithConfigIDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_InitWithConfigIDResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_ReinitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_ReinitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_g2diagnostic_ReinitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_g2diagnostic_ReinitResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022g2diagnostic.proto\022\014g2diagnostic\"*\n\022Ch" +
      "eckDBPerfRequest\022\024\n\014secondsToRun\030\001 \001(\005\"%" +
      "\n\023CheckDBPerfResponse\022\016\n\006result\030\001 \001(\t\"\033\n" +
      "\031ClearLastExceptionRequest\"\034\n\032ClearLastE" +
      "xceptionResponse\">\n\034CloseEntityListBySiz" +
      "eRequest\022\036\n\026entityListBySizeHandle\030\001 \001(\t" +
      "\"\037\n\035CloseEntityListBySizeResponse\"\020\n\016Des" +
      "troyRequest\"\021\n\017DestroyResponse\">\n\034FetchN" +
      "extEntityBySizeRequest\022\036\n\026entityListBySi" +
      "zeHandle\030\001 \001(\t\"/\n\035FetchNextEntityBySizeR" +
      "esponse\022\016\n\006result\030\001 \001(\t\"3\n\037FindEntitiesB" +
      "yFeatureIDsRequest\022\020\n\010features\030\001 \001(\t\"2\n " +
      "FindEntitiesByFeatureIDsResponse\022\016\n\006resu" +
      "lt\030\001 \001(\t\"\033\n\031GetAvailableMemoryRequest\",\n" +
      "\032GetAvailableMemoryResponse\022\016\n\006result\030\001 " +
      "\001(\003\"\034\n\032GetDataSourceCountsRequest\"-\n\033Get" +
      "DataSourceCountsResponse\022\016\n\006result\030\001 \001(\t" +
      "\"\022\n\020GetDBInfoRequest\"#\n\021GetDBInfoRespons" +
      "e\022\016\n\006result\030\001 \001(\t\"L\n\027GetEntityDetailsReq" +
      "uest\022\020\n\010entityID\030\001 \001(\003\022\037\n\027includeInterna" +
      "lFeatures\030\002 \001(\005\"*\n\030GetEntityDetailsRespo" +
      "nse\022\016\n\006result\030\001 \001(\t\"0\n\032GetEntityListBySi" +
      "zeRequest\022\022\n\nentitySize\030\001 \001(\005\"-\n\033GetEnti" +
      "tyListBySizeResponse\022\016\n\006result\030\001 \001(\t\"*\n\026" +
      "GetEntityResumeRequest\022\020\n\010entityID\030\001 \001(\003" +
      "\")\n\027GetEntityResumeResponse\022\016\n\006result\030\001 " +
      "\001(\t\"[\n\035GetEntitySizeBreakdownRequest\022\031\n\021" +
      "minimumEntitySize\030\001 \001(\005\022\037\n\027includeIntern" +
      "alFeatures\030\002 \001(\005\"0\n\036GetEntitySizeBreakdo" +
      "wnResponse\022\016\n\006result\030\001 \001(\t\"&\n\021GetFeature" +
      "Request\022\021\n\tlibFeatID\030\001 \001(\003\"$\n\022GetFeature" +
      "Response\022\016\n\006result\030\001 \001(\t\"O\n\031GetGenericFe" +
      "aturesRequest\022\023\n\013featureType\030\001 \001(\t\022\035\n\025ma" +
      "ximumEstimatedCount\030\002 \001(\005\",\n\032GetGenericF" +
      "eaturesResponse\022\016\n\006result\030\001 \001(\t\"\031\n\027GetLa" +
      "stExceptionRequest\"*\n\030GetLastExceptionRe" +
      "sponse\022\016\n\006result\030\001 \001(\t\"\035\n\033GetLastExcepti" +
      "onCodeRequest\".\n\034GetLastExceptionCodeRes" +
      "ponse\022\016\n\006result\030\001 \001(\t\"\030\n\026GetLogicalCores" +
      "Request\")\n\027GetLogicalCoresResponse\022\016\n\006re" +
      "sult\030\001 \001(\005\">\n\033GetMappingStatisticsReques" +
      "t\022\037\n\027includeInternalFeatures\030\001 \001(\005\".\n\034Ge" +
      "tMappingStatisticsResponse\022\016\n\006result\030\001 \001" +
      "(\t\"\031\n\027GetPhysicalCoresRequest\"*\n\030GetPhys" +
      "icalCoresResponse\022\016\n\006result\030\001 \001(\005\"X\n\035Get" +
      "RelationshipDetailsRequest\022\026\n\016relationsh" +
      "ipID\030\001 \001(\003\022\037\n\027includeInternalFeatures\030\002 " +
      "\001(\005\"0\n\036GetRelationshipDetailsResponse\022\016\n" +
      "\006result\030\001 \001(\t\" \n\036GetResolutionStatistics" +
      "Request\"1\n\037GetResolutionStatisticsRespon" +
      "se\022\016\n\006result\030\001 \001(\t\"\035\n\033GetTotalSystemMemo" +
      "ryRequest\".\n\034GetTotalSystemMemoryRespons" +
      "e\022\016\n\006result\030\001 \001(\003\"L\n\013InitRequest\022\022\n\nmodu" +
      "leName\030\001 \001(\t\022\021\n\tiniParams\030\002 \001(\t\022\026\n\016verbo" +
      "seLogging\030\003 \001(\005\"\016\n\014InitResponse\"n\n\027InitW" +
      "ithConfigIDRequest\022\022\n\nmoduleName\030\001 \001(\t\022\021" +
      "\n\tiniParams\030\002 \001(\t\022\024\n\014initConfigID\030\003 \001(\003\022" +
      "\026\n\016verboseLogging\030\004 \001(\005\"\032\n\030InitWithConfi" +
      "gIDResponse\"%\n\rReinitRequest\022\024\n\014initConf" +
      "igID\030\001 \001(\003\"\020\n\016ReinitResponse2\356\024\n\014G2Diagn" +
      "ostic\022T\n\013CheckDBPerf\022 .g2diagnostic.Chec" +
      "kDBPerfRequest\032!.g2diagnostic.CheckDBPer" +
      "fResponse\"\000\022i\n\022ClearLastException\022\'.g2di" +
      "agnostic.ClearLastExceptionRequest\032(.g2d" +
      "iagnostic.ClearLastExceptionResponse\"\000\022r" +
      "\n\025CloseEntityListBySize\022*.g2diagnostic.C" +
      "loseEntityListBySizeRequest\032+.g2diagnost" +
      "ic.CloseEntityListBySizeResponse\"\000\022H\n\007De" +
      "stroy\022\034.g2diagnostic.DestroyRequest\032\035.g2" +
      "diagnostic.DestroyResponse\"\000\022r\n\025FetchNex" +
      "tEntityBySize\022*.g2diagnostic.FetchNextEn" +
      "tityBySizeRequest\032+.g2diagnostic.FetchNe" +
      "xtEntityBySizeResponse\"\000\022{\n\030FindEntities" +
      "ByFeatureIDs\022-.g2diagnostic.FindEntities" +
      "ByFeatureIDsRequest\032..g2diagnostic.FindE" +
      "ntitiesByFeatureIDsResponse\"\000\022i\n\022GetAvai" +
      "lableMemory\022\'.g2diagnostic.GetAvailableM" +
      "emoryRequest\032(.g2diagnostic.GetAvailable" +
      "MemoryResponse\"\000\022l\n\023GetDataSourceCounts\022" +
      "(.g2diagnostic.GetDataSourceCountsReques" +
      "t\032).g2diagnostic.GetDataSourceCountsResp" +
      "onse\"\000\022N\n\tGetDBInfo\022\036.g2diagnostic.GetDB" +
      "InfoRequest\032\037.g2diagnostic.GetDBInfoResp" +
      "onse\"\000\022c\n\020GetEntityDetails\022%.g2diagnosti" +
      "c.GetEntityDetailsRequest\032&.g2diagnostic" +
      ".GetEntityDetailsResponse\"\000\022l\n\023GetEntity" +
      "ListBySize\022(.g2diagnostic.GetEntityListB" +
      "ySizeRequest\032).g2diagnostic.GetEntityLis" +
      "tBySizeResponse\"\000\022`\n\017GetEntityResume\022$.g" +
      "2diagnostic.GetEntityResumeRequest\032%.g2d" +
      "iagnostic.GetEntityResumeResponse\"\000\022u\n\026G" +
      "etEntitySizeBreakdown\022+.g2diagnostic.Get" +
      "EntitySizeBreakdownRequest\032,.g2diagnosti" +
      "c.GetEntitySizeBreakdownResponse\"\000\022Q\n\nGe" +
      "tFeature\022\037.g2diagnostic.GetFeatureReques" +
      "t\032 .g2diagnostic.GetFeatureResponse\"\000\022i\n" +
      "\022GetGenericFeatures\022\'.g2diagnostic.GetGe" +
      "nericFeaturesRequest\032(.g2diagnostic.GetG" +
      "enericFeaturesResponse\"\000\022c\n\020GetLastExcep" +
      "tion\022%.g2diagnostic.GetLastExceptionRequ" +
      "est\032&.g2diagnostic.GetLastExceptionRespo" +
      "nse\"\000\022o\n\024GetLastExceptionCode\022).g2diagno" +
      "stic.GetLastExceptionCodeRequest\032*.g2dia" +
      "gnostic.GetLastExceptionCodeResponse\"\000\022`" +
      "\n\017GetLogicalCores\022$.g2diagnostic.GetLogi" +
      "calCoresRequest\032%.g2diagnostic.GetLogica" +
      "lCoresResponse\"\000\022o\n\024GetMappingStatistics" +
      "\022).g2diagnostic.GetMappingStatisticsRequ" +
      "est\032*.g2diagnostic.GetMappingStatisticsR" +
      "esponse\"\000\022c\n\020GetPhysicalCores\022%.g2diagno" +
      "stic.GetPhysicalCoresRequest\032&.g2diagnos" +
      "tic.GetPhysicalCoresResponse\"\000\022u\n\026GetRel" +
      "ationshipDetails\022+.g2diagnostic.GetRelat" +
      "ionshipDetailsRequest\032,.g2diagnostic.Get" +
      "RelationshipDetailsResponse\"\000\022x\n\027GetReso" +
      "lutionStatistics\022,.g2diagnostic.GetResol" +
      "utionStatisticsRequest\032-.g2diagnostic.Ge" +
      "tResolutionStatisticsResponse\"\000\022o\n\024GetTo" +
      "talSystemMemory\022).g2diagnostic.GetTotalS" +
      "ystemMemoryRequest\032*.g2diagnostic.GetTot" +
      "alSystemMemoryResponse\"\000\022?\n\004Init\022\031.g2dia" +
      "gnostic.InitRequest\032\032.g2diagnostic.InitR" +
      "esponse\"\000\022c\n\020InitWithConfigID\022%.g2diagno" +
      "stic.InitWithConfigIDRequest\032&.g2diagnos" +
      "tic.InitWithConfigIDResponse\"\000\022E\n\006Reinit" +
      "\022\033.g2diagnostic.ReinitRequest\032\034.g2diagno" +
      "stic.ReinitResponse\"\000Bn\n\'com.senzing.g2." +
      "engine.grpc.G2DiagnosticB\021G2DiagnosticPr" +
      "otoP\001Z.github.com/senzing/g2-sdk-go-grpc" +
      "/g2diagnosticb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_g2diagnostic_CheckDBPerfRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_g2diagnostic_CheckDBPerfRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_CheckDBPerfRequest_descriptor,
        new java.lang.String[] { "SecondsToRun", });
    internal_static_g2diagnostic_CheckDBPerfResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_g2diagnostic_CheckDBPerfResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_CheckDBPerfResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_ClearLastExceptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_g2diagnostic_ClearLastExceptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_ClearLastExceptionRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_ClearLastExceptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_g2diagnostic_ClearLastExceptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_ClearLastExceptionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_CloseEntityListBySizeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_g2diagnostic_CloseEntityListBySizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_CloseEntityListBySizeRequest_descriptor,
        new java.lang.String[] { "EntityListBySizeHandle", });
    internal_static_g2diagnostic_CloseEntityListBySizeResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_g2diagnostic_CloseEntityListBySizeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_CloseEntityListBySizeResponse_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_DestroyRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_g2diagnostic_DestroyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_DestroyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_DestroyResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_g2diagnostic_DestroyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_DestroyResponse_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_FetchNextEntityBySizeRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_g2diagnostic_FetchNextEntityBySizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_FetchNextEntityBySizeRequest_descriptor,
        new java.lang.String[] { "EntityListBySizeHandle", });
    internal_static_g2diagnostic_FetchNextEntityBySizeResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_g2diagnostic_FetchNextEntityBySizeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_FetchNextEntityBySizeResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_FindEntitiesByFeatureIDsRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_g2diagnostic_FindEntitiesByFeatureIDsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_FindEntitiesByFeatureIDsRequest_descriptor,
        new java.lang.String[] { "Features", });
    internal_static_g2diagnostic_FindEntitiesByFeatureIDsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_g2diagnostic_FindEntitiesByFeatureIDsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_FindEntitiesByFeatureIDsResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetAvailableMemoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_g2diagnostic_GetAvailableMemoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetAvailableMemoryRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_GetAvailableMemoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_g2diagnostic_GetAvailableMemoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetAvailableMemoryResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetDataSourceCountsRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_g2diagnostic_GetDataSourceCountsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetDataSourceCountsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_GetDataSourceCountsResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_g2diagnostic_GetDataSourceCountsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetDataSourceCountsResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetDBInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_g2diagnostic_GetDBInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetDBInfoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_GetDBInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_g2diagnostic_GetDBInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetDBInfoResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetEntityDetailsRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_g2diagnostic_GetEntityDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetEntityDetailsRequest_descriptor,
        new java.lang.String[] { "EntityID", "IncludeInternalFeatures", });
    internal_static_g2diagnostic_GetEntityDetailsResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_g2diagnostic_GetEntityDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetEntityDetailsResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetEntityListBySizeRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_g2diagnostic_GetEntityListBySizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetEntityListBySizeRequest_descriptor,
        new java.lang.String[] { "EntitySize", });
    internal_static_g2diagnostic_GetEntityListBySizeResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_g2diagnostic_GetEntityListBySizeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetEntityListBySizeResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetEntityResumeRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_g2diagnostic_GetEntityResumeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetEntityResumeRequest_descriptor,
        new java.lang.String[] { "EntityID", });
    internal_static_g2diagnostic_GetEntityResumeResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_g2diagnostic_GetEntityResumeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetEntityResumeResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetEntitySizeBreakdownRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_g2diagnostic_GetEntitySizeBreakdownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetEntitySizeBreakdownRequest_descriptor,
        new java.lang.String[] { "MinimumEntitySize", "IncludeInternalFeatures", });
    internal_static_g2diagnostic_GetEntitySizeBreakdownResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_g2diagnostic_GetEntitySizeBreakdownResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetEntitySizeBreakdownResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetFeatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_g2diagnostic_GetFeatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetFeatureRequest_descriptor,
        new java.lang.String[] { "LibFeatID", });
    internal_static_g2diagnostic_GetFeatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_g2diagnostic_GetFeatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetFeatureResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetGenericFeaturesRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_g2diagnostic_GetGenericFeaturesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetGenericFeaturesRequest_descriptor,
        new java.lang.String[] { "FeatureType", "MaximumEstimatedCount", });
    internal_static_g2diagnostic_GetGenericFeaturesResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_g2diagnostic_GetGenericFeaturesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetGenericFeaturesResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetLastExceptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_g2diagnostic_GetLastExceptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetLastExceptionRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_GetLastExceptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_g2diagnostic_GetLastExceptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetLastExceptionResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetLastExceptionCodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_g2diagnostic_GetLastExceptionCodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetLastExceptionCodeRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_GetLastExceptionCodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_g2diagnostic_GetLastExceptionCodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetLastExceptionCodeResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetLogicalCoresRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_g2diagnostic_GetLogicalCoresRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetLogicalCoresRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_GetLogicalCoresResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_g2diagnostic_GetLogicalCoresResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetLogicalCoresResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetMappingStatisticsRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_g2diagnostic_GetMappingStatisticsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetMappingStatisticsRequest_descriptor,
        new java.lang.String[] { "IncludeInternalFeatures", });
    internal_static_g2diagnostic_GetMappingStatisticsResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_g2diagnostic_GetMappingStatisticsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetMappingStatisticsResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetPhysicalCoresRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_g2diagnostic_GetPhysicalCoresRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetPhysicalCoresRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_GetPhysicalCoresResponse_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_g2diagnostic_GetPhysicalCoresResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetPhysicalCoresResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetRelationshipDetailsRequest_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_g2diagnostic_GetRelationshipDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetRelationshipDetailsRequest_descriptor,
        new java.lang.String[] { "RelationshipID", "IncludeInternalFeatures", });
    internal_static_g2diagnostic_GetRelationshipDetailsResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_g2diagnostic_GetRelationshipDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetRelationshipDetailsResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetResolutionStatisticsRequest_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_g2diagnostic_GetResolutionStatisticsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetResolutionStatisticsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_GetResolutionStatisticsResponse_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_g2diagnostic_GetResolutionStatisticsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetResolutionStatisticsResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_GetTotalSystemMemoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_g2diagnostic_GetTotalSystemMemoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetTotalSystemMemoryRequest_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_GetTotalSystemMemoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_g2diagnostic_GetTotalSystemMemoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_GetTotalSystemMemoryResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_g2diagnostic_InitRequest_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_g2diagnostic_InitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_InitRequest_descriptor,
        new java.lang.String[] { "ModuleName", "IniParams", "VerboseLogging", });
    internal_static_g2diagnostic_InitResponse_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_g2diagnostic_InitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_InitResponse_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_InitWithConfigIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_g2diagnostic_InitWithConfigIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_InitWithConfigIDRequest_descriptor,
        new java.lang.String[] { "ModuleName", "IniParams", "InitConfigID", "VerboseLogging", });
    internal_static_g2diagnostic_InitWithConfigIDResponse_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_g2diagnostic_InitWithConfigIDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_InitWithConfigIDResponse_descriptor,
        new java.lang.String[] { });
    internal_static_g2diagnostic_ReinitRequest_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_g2diagnostic_ReinitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_ReinitRequest_descriptor,
        new java.lang.String[] { "InitConfigID", });
    internal_static_g2diagnostic_ReinitResponse_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_g2diagnostic_ReinitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_g2diagnostic_ReinitResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
