// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: g2engine.proto

package com.senzing.g2.engine.grpc.G2Engine;

public interface ProcessWithResponseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:g2engine.ProcessWithResponseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string record = 1;</code>
   * @return The record.
   */
  java.lang.String getRecord();
  /**
   * <code>string record = 1;</code>
   * @return The bytes for record.
   */
  com.google.protobuf.ByteString
      getRecordBytes();
}
