<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: g2configmgr.proto

namespace G2configmgr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>g2configmgr.AddConfigRequest</code>
 */
class AddConfigRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string configStr = 1;</code>
     */
    protected $configStr = '';
    /**
     * Generated from protobuf field <code>string configComments = 2;</code>
     */
    protected $configComments = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $configStr
     *     @type string $configComments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\G2Configmgr::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string configStr = 1;</code>
     * @return string
     */
    public function getConfigStr()
    {
        return $this->configStr;
    }

    /**
     * Generated from protobuf field <code>string configStr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConfigStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->configStr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string configComments = 2;</code>
     * @return string
     */
    public function getConfigComments()
    {
        return $this->configComments;
    }

    /**
     * Generated from protobuf field <code>string configComments = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setConfigComments($var)
    {
        GPBUtil::checkString($var, True);
        $this->configComments = $var;

        return $this;
    }

}

