/**
 * @fileoverview gRPC-Web generated client stub for szconfig
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: szconfig.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as szconfig_pb from './szconfig_pb'; // proto import: "szconfig.proto"


export class SzConfigClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAddDataSource = new grpcWeb.MethodDescriptor(
    '/szconfig.SzConfig/AddDataSource',
    grpcWeb.MethodType.UNARY,
    szconfig_pb.AddDataSourceRequest,
    szconfig_pb.AddDataSourceResponse,
    (request: szconfig_pb.AddDataSourceRequest) => {
      return request.serializeBinary();
    },
    szconfig_pb.AddDataSourceResponse.deserializeBinary
  );

  addDataSource(
    request: szconfig_pb.AddDataSourceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<szconfig_pb.AddDataSourceResponse>;

  addDataSource(
    request: szconfig_pb.AddDataSourceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: szconfig_pb.AddDataSourceResponse) => void): grpcWeb.ClientReadableStream<szconfig_pb.AddDataSourceResponse>;

  addDataSource(
    request: szconfig_pb.AddDataSourceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: szconfig_pb.AddDataSourceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/szconfig.SzConfig/AddDataSource',
        request,
        metadata || {},
        this.methodDescriptorAddDataSource,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/szconfig.SzConfig/AddDataSource',
    request,
    metadata || {},
    this.methodDescriptorAddDataSource);
  }

  methodDescriptorCloseConfig = new grpcWeb.MethodDescriptor(
    '/szconfig.SzConfig/CloseConfig',
    grpcWeb.MethodType.UNARY,
    szconfig_pb.CloseConfigRequest,
    szconfig_pb.CloseConfigResponse,
    (request: szconfig_pb.CloseConfigRequest) => {
      return request.serializeBinary();
    },
    szconfig_pb.CloseConfigResponse.deserializeBinary
  );

  closeConfig(
    request: szconfig_pb.CloseConfigRequest,
    metadata?: grpcWeb.Metadata | null): Promise<szconfig_pb.CloseConfigResponse>;

  closeConfig(
    request: szconfig_pb.CloseConfigRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: szconfig_pb.CloseConfigResponse) => void): grpcWeb.ClientReadableStream<szconfig_pb.CloseConfigResponse>;

  closeConfig(
    request: szconfig_pb.CloseConfigRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: szconfig_pb.CloseConfigResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/szconfig.SzConfig/CloseConfig',
        request,
        metadata || {},
        this.methodDescriptorCloseConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/szconfig.SzConfig/CloseConfig',
    request,
    metadata || {},
    this.methodDescriptorCloseConfig);
  }

  methodDescriptorCreateConfig = new grpcWeb.MethodDescriptor(
    '/szconfig.SzConfig/CreateConfig',
    grpcWeb.MethodType.UNARY,
    szconfig_pb.CreateConfigRequest,
    szconfig_pb.CreateConfigResponse,
    (request: szconfig_pb.CreateConfigRequest) => {
      return request.serializeBinary();
    },
    szconfig_pb.CreateConfigResponse.deserializeBinary
  );

  createConfig(
    request: szconfig_pb.CreateConfigRequest,
    metadata?: grpcWeb.Metadata | null): Promise<szconfig_pb.CreateConfigResponse>;

  createConfig(
    request: szconfig_pb.CreateConfigRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: szconfig_pb.CreateConfigResponse) => void): grpcWeb.ClientReadableStream<szconfig_pb.CreateConfigResponse>;

  createConfig(
    request: szconfig_pb.CreateConfigRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: szconfig_pb.CreateConfigResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/szconfig.SzConfig/CreateConfig',
        request,
        metadata || {},
        this.methodDescriptorCreateConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/szconfig.SzConfig/CreateConfig',
    request,
    metadata || {},
    this.methodDescriptorCreateConfig);
  }

  methodDescriptorDeleteDataSource = new grpcWeb.MethodDescriptor(
    '/szconfig.SzConfig/DeleteDataSource',
    grpcWeb.MethodType.UNARY,
    szconfig_pb.DeleteDataSourceRequest,
    szconfig_pb.DeleteDataSourceResponse,
    (request: szconfig_pb.DeleteDataSourceRequest) => {
      return request.serializeBinary();
    },
    szconfig_pb.DeleteDataSourceResponse.deserializeBinary
  );

  deleteDataSource(
    request: szconfig_pb.DeleteDataSourceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<szconfig_pb.DeleteDataSourceResponse>;

  deleteDataSource(
    request: szconfig_pb.DeleteDataSourceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: szconfig_pb.DeleteDataSourceResponse) => void): grpcWeb.ClientReadableStream<szconfig_pb.DeleteDataSourceResponse>;

  deleteDataSource(
    request: szconfig_pb.DeleteDataSourceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: szconfig_pb.DeleteDataSourceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/szconfig.SzConfig/DeleteDataSource',
        request,
        metadata || {},
        this.methodDescriptorDeleteDataSource,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/szconfig.SzConfig/DeleteDataSource',
    request,
    metadata || {},
    this.methodDescriptorDeleteDataSource);
  }

  methodDescriptorExportConfig = new grpcWeb.MethodDescriptor(
    '/szconfig.SzConfig/ExportConfig',
    grpcWeb.MethodType.UNARY,
    szconfig_pb.ExportConfigRequest,
    szconfig_pb.ExportConfigResponse,
    (request: szconfig_pb.ExportConfigRequest) => {
      return request.serializeBinary();
    },
    szconfig_pb.ExportConfigResponse.deserializeBinary
  );

  exportConfig(
    request: szconfig_pb.ExportConfigRequest,
    metadata?: grpcWeb.Metadata | null): Promise<szconfig_pb.ExportConfigResponse>;

  exportConfig(
    request: szconfig_pb.ExportConfigRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: szconfig_pb.ExportConfigResponse) => void): grpcWeb.ClientReadableStream<szconfig_pb.ExportConfigResponse>;

  exportConfig(
    request: szconfig_pb.ExportConfigRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: szconfig_pb.ExportConfigResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/szconfig.SzConfig/ExportConfig',
        request,
        metadata || {},
        this.methodDescriptorExportConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/szconfig.SzConfig/ExportConfig',
    request,
    metadata || {},
    this.methodDescriptorExportConfig);
  }

  methodDescriptorGetDataSources = new grpcWeb.MethodDescriptor(
    '/szconfig.SzConfig/GetDataSources',
    grpcWeb.MethodType.UNARY,
    szconfig_pb.GetDataSourcesRequest,
    szconfig_pb.GetDataSourcesResponse,
    (request: szconfig_pb.GetDataSourcesRequest) => {
      return request.serializeBinary();
    },
    szconfig_pb.GetDataSourcesResponse.deserializeBinary
  );

  getDataSources(
    request: szconfig_pb.GetDataSourcesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<szconfig_pb.GetDataSourcesResponse>;

  getDataSources(
    request: szconfig_pb.GetDataSourcesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: szconfig_pb.GetDataSourcesResponse) => void): grpcWeb.ClientReadableStream<szconfig_pb.GetDataSourcesResponse>;

  getDataSources(
    request: szconfig_pb.GetDataSourcesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: szconfig_pb.GetDataSourcesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/szconfig.SzConfig/GetDataSources',
        request,
        metadata || {},
        this.methodDescriptorGetDataSources,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/szconfig.SzConfig/GetDataSources',
    request,
    metadata || {},
    this.methodDescriptorGetDataSources);
  }

  methodDescriptorImportConfig = new grpcWeb.MethodDescriptor(
    '/szconfig.SzConfig/ImportConfig',
    grpcWeb.MethodType.UNARY,
    szconfig_pb.ImportConfigRequest,
    szconfig_pb.ImportConfigResponse,
    (request: szconfig_pb.ImportConfigRequest) => {
      return request.serializeBinary();
    },
    szconfig_pb.ImportConfigResponse.deserializeBinary
  );

  importConfig(
    request: szconfig_pb.ImportConfigRequest,
    metadata?: grpcWeb.Metadata | null): Promise<szconfig_pb.ImportConfigResponse>;

  importConfig(
    request: szconfig_pb.ImportConfigRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: szconfig_pb.ImportConfigResponse) => void): grpcWeb.ClientReadableStream<szconfig_pb.ImportConfigResponse>;

  importConfig(
    request: szconfig_pb.ImportConfigRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: szconfig_pb.ImportConfigResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/szconfig.SzConfig/ImportConfig',
        request,
        metadata || {},
        this.methodDescriptorImportConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/szconfig.SzConfig/ImportConfig',
    request,
    metadata || {},
    this.methodDescriptorImportConfig);
  }

}

