<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: g2hasher.proto

namespace G2hasher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>g2hasher.GetLastExceptionCodeRequest</code>
 */
class GetLastExceptionCodeRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\G2Hasher::initOnce();
        parent::__construct($data);
    }

}

