// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: g2product.proto

package com.senzing.g2.engine.grpc.G2Product;

public interface LicenseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:g2product.LicenseRequest)
    com.google.protobuf.MessageOrBuilder {
}
