// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: szdiagnostic.proto

#include "szdiagnostic.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace szdiagnostic {
      template <typename>
PROTOBUF_CONSTEXPR ReinitializeResponse::ReinitializeResponse(::_pbi::ConstantInitialized) {}
struct ReinitializeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReinitializeResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReinitializeResponseDefaultTypeInternal() {}
  union {
    ReinitializeResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReinitializeResponseDefaultTypeInternal _ReinitializeResponse_default_instance_;

inline constexpr ReinitializeRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : configid_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReinitializeRequest::ReinitializeRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ReinitializeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReinitializeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReinitializeRequestDefaultTypeInternal() {}
  union {
    ReinitializeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReinitializeRequestDefaultTypeInternal _ReinitializeRequest_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR PurgeRepositoryResponse::PurgeRepositoryResponse(::_pbi::ConstantInitialized) {}
struct PurgeRepositoryResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PurgeRepositoryResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PurgeRepositoryResponseDefaultTypeInternal() {}
  union {
    PurgeRepositoryResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PurgeRepositoryResponseDefaultTypeInternal _PurgeRepositoryResponse_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR PurgeRepositoryRequest::PurgeRepositoryRequest(::_pbi::ConstantInitialized) {}
struct PurgeRepositoryRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PurgeRepositoryRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PurgeRepositoryRequestDefaultTypeInternal() {}
  union {
    PurgeRepositoryRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PurgeRepositoryRequestDefaultTypeInternal _PurgeRepositoryRequest_default_instance_;

inline constexpr GetFeatureResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetFeatureResponse::GetFeatureResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetFeatureResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetFeatureResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetFeatureResponseDefaultTypeInternal() {}
  union {
    GetFeatureResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetFeatureResponseDefaultTypeInternal _GetFeatureResponse_default_instance_;

inline constexpr GetFeatureRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : featureid_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetFeatureRequest::GetFeatureRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetFeatureRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetFeatureRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetFeatureRequestDefaultTypeInternal() {}
  union {
    GetFeatureRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetFeatureRequestDefaultTypeInternal _GetFeatureRequest_default_instance_;

inline constexpr GetDatastoreInfoResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetDatastoreInfoResponse::GetDatastoreInfoResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetDatastoreInfoResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetDatastoreInfoResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetDatastoreInfoResponseDefaultTypeInternal() {}
  union {
    GetDatastoreInfoResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetDatastoreInfoResponseDefaultTypeInternal _GetDatastoreInfoResponse_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR GetDatastoreInfoRequest::GetDatastoreInfoRequest(::_pbi::ConstantInitialized) {}
struct GetDatastoreInfoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetDatastoreInfoRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetDatastoreInfoRequestDefaultTypeInternal() {}
  union {
    GetDatastoreInfoRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetDatastoreInfoRequestDefaultTypeInternal _GetDatastoreInfoRequest_default_instance_;

inline constexpr CheckDatastorePerformanceResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CheckDatastorePerformanceResponse::CheckDatastorePerformanceResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CheckDatastorePerformanceResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckDatastorePerformanceResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckDatastorePerformanceResponseDefaultTypeInternal() {}
  union {
    CheckDatastorePerformanceResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckDatastorePerformanceResponseDefaultTypeInternal _CheckDatastorePerformanceResponse_default_instance_;

inline constexpr CheckDatastorePerformanceRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : secondstorun_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CheckDatastorePerformanceRequest::CheckDatastorePerformanceRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CheckDatastorePerformanceRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckDatastorePerformanceRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckDatastorePerformanceRequestDefaultTypeInternal() {}
  union {
    CheckDatastorePerformanceRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckDatastorePerformanceRequestDefaultTypeInternal _CheckDatastorePerformanceRequest_default_instance_;
}  // namespace szdiagnostic
static ::_pb::Metadata file_level_metadata_szdiagnostic_2eproto[10];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_szdiagnostic_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_szdiagnostic_2eproto = nullptr;
const ::uint32_t TableStruct_szdiagnostic_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::CheckDatastorePerformanceRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::CheckDatastorePerformanceRequest, _impl_.secondstorun_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::CheckDatastorePerformanceResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::CheckDatastorePerformanceResponse, _impl_.result_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::GetDatastoreInfoRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::GetDatastoreInfoResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::GetDatastoreInfoResponse, _impl_.result_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::GetFeatureRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::GetFeatureRequest, _impl_.featureid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::GetFeatureResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::GetFeatureResponse, _impl_.result_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::PurgeRepositoryRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::PurgeRepositoryResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::ReinitializeRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::ReinitializeRequest, _impl_.configid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::szdiagnostic::ReinitializeResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::szdiagnostic::CheckDatastorePerformanceRequest)},
        {9, -1, -1, sizeof(::szdiagnostic::CheckDatastorePerformanceResponse)},
        {18, -1, -1, sizeof(::szdiagnostic::GetDatastoreInfoRequest)},
        {26, -1, -1, sizeof(::szdiagnostic::GetDatastoreInfoResponse)},
        {35, -1, -1, sizeof(::szdiagnostic::GetFeatureRequest)},
        {44, -1, -1, sizeof(::szdiagnostic::GetFeatureResponse)},
        {53, -1, -1, sizeof(::szdiagnostic::PurgeRepositoryRequest)},
        {61, -1, -1, sizeof(::szdiagnostic::PurgeRepositoryResponse)},
        {69, -1, -1, sizeof(::szdiagnostic::ReinitializeRequest)},
        {78, -1, -1, sizeof(::szdiagnostic::ReinitializeResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::szdiagnostic::_CheckDatastorePerformanceRequest_default_instance_._instance,
    &::szdiagnostic::_CheckDatastorePerformanceResponse_default_instance_._instance,
    &::szdiagnostic::_GetDatastoreInfoRequest_default_instance_._instance,
    &::szdiagnostic::_GetDatastoreInfoResponse_default_instance_._instance,
    &::szdiagnostic::_GetFeatureRequest_default_instance_._instance,
    &::szdiagnostic::_GetFeatureResponse_default_instance_._instance,
    &::szdiagnostic::_PurgeRepositoryRequest_default_instance_._instance,
    &::szdiagnostic::_PurgeRepositoryResponse_default_instance_._instance,
    &::szdiagnostic::_ReinitializeRequest_default_instance_._instance,
    &::szdiagnostic::_ReinitializeResponse_default_instance_._instance,
};
const char descriptor_table_protodef_szdiagnostic_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\022szdiagnostic.proto\022\014szdiagnostic\"8\n Ch"
    "eckDatastorePerformanceRequest\022\024\n\014second"
    "sToRun\030\001 \001(\005\"3\n!CheckDatastorePerformanc"
    "eResponse\022\016\n\006result\030\001 \001(\t\"\031\n\027GetDatastor"
    "eInfoRequest\"*\n\030GetDatastoreInfoResponse"
    "\022\016\n\006result\030\001 \001(\t\"&\n\021GetFeatureRequest\022\021\n"
    "\tfeatureId\030\001 \001(\003\"$\n\022GetFeatureResponse\022\016"
    "\n\006result\030\001 \001(\t\"\030\n\026PurgeRepositoryRequest"
    "\"\031\n\027PurgeRepositoryResponse\"\'\n\023Reinitial"
    "izeRequest\022\020\n\010configId\030\001 \001(\003\"\026\n\024Reinitia"
    "lizeResponse2\201\004\n\014SzDiagnostic\022~\n\031CheckDa"
    "tastorePerformance\022..szdiagnostic.CheckD"
    "atastorePerformanceRequest\032/.szdiagnosti"
    "c.CheckDatastorePerformanceResponse\"\000\022c\n"
    "\020GetDatastoreInfo\022%.szdiagnostic.GetData"
    "storeInfoRequest\032&.szdiagnostic.GetDatas"
    "toreInfoResponse\"\000\022Q\n\nGetFeature\022\037.szdia"
    "gnostic.GetFeatureRequest\032 .szdiagnostic"
    ".GetFeatureResponse\"\000\022`\n\017PurgeRepository"
    "\022$.szdiagnostic.PurgeRepositoryRequest\032%"
    ".szdiagnostic.PurgeRepositoryResponse\"\000\022"
    "W\n\014Reinitialize\022!.szdiagnostic.Reinitial"
    "izeRequest\032\".szdiagnostic.ReinitializeRe"
    "sponse\"\000Bs\n\'com.senzing.sz.engine.grpc.S"
    "zDiagnosticB\021SzDiagnosticProtoZ5github.c"
    "om/senzing-garage/sz-sdk-go-grpc/szdiagn"
    "osticb\006proto3"
};
static ::absl::once_flag descriptor_table_szdiagnostic_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_szdiagnostic_2eproto = {
    false,
    false,
    1053,
    descriptor_table_protodef_szdiagnostic_2eproto,
    "szdiagnostic.proto",
    &descriptor_table_szdiagnostic_2eproto_once,
    nullptr,
    0,
    10,
    schemas,
    file_default_instances,
    TableStruct_szdiagnostic_2eproto::offsets,
    file_level_metadata_szdiagnostic_2eproto,
    file_level_enum_descriptors_szdiagnostic_2eproto,
    file_level_service_descriptors_szdiagnostic_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_szdiagnostic_2eproto_getter() {
  return &descriptor_table_szdiagnostic_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_szdiagnostic_2eproto(&descriptor_table_szdiagnostic_2eproto);
namespace szdiagnostic {
// ===================================================================

class CheckDatastorePerformanceRequest::_Internal {
 public:
};

CheckDatastorePerformanceRequest::CheckDatastorePerformanceRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:szdiagnostic.CheckDatastorePerformanceRequest)
}
CheckDatastorePerformanceRequest::CheckDatastorePerformanceRequest(
    ::google::protobuf::Arena* arena, const CheckDatastorePerformanceRequest& from)
    : CheckDatastorePerformanceRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CheckDatastorePerformanceRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CheckDatastorePerformanceRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.secondstorun_ = {};
}
CheckDatastorePerformanceRequest::~CheckDatastorePerformanceRequest() {
  // @@protoc_insertion_point(destructor:szdiagnostic.CheckDatastorePerformanceRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CheckDatastorePerformanceRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CheckDatastorePerformanceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:szdiagnostic.CheckDatastorePerformanceRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.secondstorun_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CheckDatastorePerformanceRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CheckDatastorePerformanceRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CheckDatastorePerformanceRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 secondsToRun = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CheckDatastorePerformanceRequest, _impl_.secondstorun_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CheckDatastorePerformanceRequest, _impl_.secondstorun_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 secondsToRun = 1;
    {PROTOBUF_FIELD_OFFSET(CheckDatastorePerformanceRequest, _impl_.secondstorun_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CheckDatastorePerformanceRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:szdiagnostic.CheckDatastorePerformanceRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 secondsToRun = 1;
  if (this->_internal_secondstorun() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_secondstorun(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:szdiagnostic.CheckDatastorePerformanceRequest)
  return target;
}

::size_t CheckDatastorePerformanceRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:szdiagnostic.CheckDatastorePerformanceRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 secondsToRun = 1;
  if (this->_internal_secondstorun() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_secondstorun());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CheckDatastorePerformanceRequest::_class_data_ = {
    CheckDatastorePerformanceRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CheckDatastorePerformanceRequest::GetClassData() const {
  return &_class_data_;
}

void CheckDatastorePerformanceRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CheckDatastorePerformanceRequest*>(&to_msg);
  auto& from = static_cast<const CheckDatastorePerformanceRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:szdiagnostic.CheckDatastorePerformanceRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_secondstorun() != 0) {
    _this->_internal_set_secondstorun(from._internal_secondstorun());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CheckDatastorePerformanceRequest::CopyFrom(const CheckDatastorePerformanceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:szdiagnostic.CheckDatastorePerformanceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CheckDatastorePerformanceRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CheckDatastorePerformanceRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CheckDatastorePerformanceRequest::InternalSwap(CheckDatastorePerformanceRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.secondstorun_, other->_impl_.secondstorun_);
}

::google::protobuf::Metadata CheckDatastorePerformanceRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_szdiagnostic_2eproto_getter, &descriptor_table_szdiagnostic_2eproto_once,
      file_level_metadata_szdiagnostic_2eproto[0]);
}
// ===================================================================

class CheckDatastorePerformanceResponse::_Internal {
 public:
};

CheckDatastorePerformanceResponse::CheckDatastorePerformanceResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:szdiagnostic.CheckDatastorePerformanceResponse)
}
inline PROTOBUF_NDEBUG_INLINE CheckDatastorePerformanceResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : result_(arena, from.result_),
        _cached_size_{0} {}

CheckDatastorePerformanceResponse::CheckDatastorePerformanceResponse(
    ::google::protobuf::Arena* arena,
    const CheckDatastorePerformanceResponse& from)
    : ::google::protobuf::Message(arena) {
  CheckDatastorePerformanceResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:szdiagnostic.CheckDatastorePerformanceResponse)
}
inline PROTOBUF_NDEBUG_INLINE CheckDatastorePerformanceResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : result_(arena),
        _cached_size_{0} {}

inline void CheckDatastorePerformanceResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CheckDatastorePerformanceResponse::~CheckDatastorePerformanceResponse() {
  // @@protoc_insertion_point(destructor:szdiagnostic.CheckDatastorePerformanceResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CheckDatastorePerformanceResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.result_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CheckDatastorePerformanceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:szdiagnostic.CheckDatastorePerformanceResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CheckDatastorePerformanceResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 61, 2> CheckDatastorePerformanceResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CheckDatastorePerformanceResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string result = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CheckDatastorePerformanceResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string result = 1;
    {PROTOBUF_FIELD_OFFSET(CheckDatastorePerformanceResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\56\6\0\0\0\0\0\0"
    "szdiagnostic.CheckDatastorePerformanceResponse"
    "result"
  }},
};

::uint8_t* CheckDatastorePerformanceResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:szdiagnostic.CheckDatastorePerformanceResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string result = 1;
  if (!this->_internal_result().empty()) {
    const std::string& _s = this->_internal_result();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "szdiagnostic.CheckDatastorePerformanceResponse.result");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:szdiagnostic.CheckDatastorePerformanceResponse)
  return target;
}

::size_t CheckDatastorePerformanceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:szdiagnostic.CheckDatastorePerformanceResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string result = 1;
  if (!this->_internal_result().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CheckDatastorePerformanceResponse::_class_data_ = {
    CheckDatastorePerformanceResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CheckDatastorePerformanceResponse::GetClassData() const {
  return &_class_data_;
}

void CheckDatastorePerformanceResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CheckDatastorePerformanceResponse*>(&to_msg);
  auto& from = static_cast<const CheckDatastorePerformanceResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:szdiagnostic.CheckDatastorePerformanceResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_result().empty()) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CheckDatastorePerformanceResponse::CopyFrom(const CheckDatastorePerformanceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:szdiagnostic.CheckDatastorePerformanceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CheckDatastorePerformanceResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CheckDatastorePerformanceResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CheckDatastorePerformanceResponse::InternalSwap(CheckDatastorePerformanceResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.result_, &other->_impl_.result_, arena);
}

::google::protobuf::Metadata CheckDatastorePerformanceResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_szdiagnostic_2eproto_getter, &descriptor_table_szdiagnostic_2eproto_once,
      file_level_metadata_szdiagnostic_2eproto[1]);
}
// ===================================================================

class GetDatastoreInfoRequest::_Internal {
 public:
};

GetDatastoreInfoRequest::GetDatastoreInfoRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:szdiagnostic.GetDatastoreInfoRequest)
}
GetDatastoreInfoRequest::GetDatastoreInfoRequest(
    ::google::protobuf::Arena* arena,
    const GetDatastoreInfoRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  GetDatastoreInfoRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:szdiagnostic.GetDatastoreInfoRequest)
}









::google::protobuf::Metadata GetDatastoreInfoRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_szdiagnostic_2eproto_getter, &descriptor_table_szdiagnostic_2eproto_once,
      file_level_metadata_szdiagnostic_2eproto[2]);
}
// ===================================================================

class GetDatastoreInfoResponse::_Internal {
 public:
};

GetDatastoreInfoResponse::GetDatastoreInfoResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:szdiagnostic.GetDatastoreInfoResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetDatastoreInfoResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : result_(arena, from.result_),
        _cached_size_{0} {}

GetDatastoreInfoResponse::GetDatastoreInfoResponse(
    ::google::protobuf::Arena* arena,
    const GetDatastoreInfoResponse& from)
    : ::google::protobuf::Message(arena) {
  GetDatastoreInfoResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:szdiagnostic.GetDatastoreInfoResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetDatastoreInfoResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : result_(arena),
        _cached_size_{0} {}

inline void GetDatastoreInfoResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetDatastoreInfoResponse::~GetDatastoreInfoResponse() {
  // @@protoc_insertion_point(destructor:szdiagnostic.GetDatastoreInfoResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetDatastoreInfoResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.result_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GetDatastoreInfoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:szdiagnostic.GetDatastoreInfoResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GetDatastoreInfoResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 52, 2> GetDatastoreInfoResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetDatastoreInfoResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string result = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetDatastoreInfoResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string result = 1;
    {PROTOBUF_FIELD_OFFSET(GetDatastoreInfoResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\45\6\0\0\0\0\0\0"
    "szdiagnostic.GetDatastoreInfoResponse"
    "result"
  }},
};

::uint8_t* GetDatastoreInfoResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:szdiagnostic.GetDatastoreInfoResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string result = 1;
  if (!this->_internal_result().empty()) {
    const std::string& _s = this->_internal_result();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "szdiagnostic.GetDatastoreInfoResponse.result");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:szdiagnostic.GetDatastoreInfoResponse)
  return target;
}

::size_t GetDatastoreInfoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:szdiagnostic.GetDatastoreInfoResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string result = 1;
  if (!this->_internal_result().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GetDatastoreInfoResponse::_class_data_ = {
    GetDatastoreInfoResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GetDatastoreInfoResponse::GetClassData() const {
  return &_class_data_;
}

void GetDatastoreInfoResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GetDatastoreInfoResponse*>(&to_msg);
  auto& from = static_cast<const GetDatastoreInfoResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:szdiagnostic.GetDatastoreInfoResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_result().empty()) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetDatastoreInfoResponse::CopyFrom(const GetDatastoreInfoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:szdiagnostic.GetDatastoreInfoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GetDatastoreInfoResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GetDatastoreInfoResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GetDatastoreInfoResponse::InternalSwap(GetDatastoreInfoResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.result_, &other->_impl_.result_, arena);
}

::google::protobuf::Metadata GetDatastoreInfoResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_szdiagnostic_2eproto_getter, &descriptor_table_szdiagnostic_2eproto_once,
      file_level_metadata_szdiagnostic_2eproto[3]);
}
// ===================================================================

class GetFeatureRequest::_Internal {
 public:
};

GetFeatureRequest::GetFeatureRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:szdiagnostic.GetFeatureRequest)
}
GetFeatureRequest::GetFeatureRequest(
    ::google::protobuf::Arena* arena, const GetFeatureRequest& from)
    : GetFeatureRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GetFeatureRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetFeatureRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.featureid_ = {};
}
GetFeatureRequest::~GetFeatureRequest() {
  // @@protoc_insertion_point(destructor:szdiagnostic.GetFeatureRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetFeatureRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GetFeatureRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:szdiagnostic.GetFeatureRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.featureid_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GetFeatureRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetFeatureRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetFeatureRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 featureId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GetFeatureRequest, _impl_.featureid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetFeatureRequest, _impl_.featureid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 featureId = 1;
    {PROTOBUF_FIELD_OFFSET(GetFeatureRequest, _impl_.featureid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* GetFeatureRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:szdiagnostic.GetFeatureRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 featureId = 1;
  if (this->_internal_featureid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_featureid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:szdiagnostic.GetFeatureRequest)
  return target;
}

::size_t GetFeatureRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:szdiagnostic.GetFeatureRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 featureId = 1;
  if (this->_internal_featureid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_featureid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GetFeatureRequest::_class_data_ = {
    GetFeatureRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GetFeatureRequest::GetClassData() const {
  return &_class_data_;
}

void GetFeatureRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GetFeatureRequest*>(&to_msg);
  auto& from = static_cast<const GetFeatureRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:szdiagnostic.GetFeatureRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_featureid() != 0) {
    _this->_internal_set_featureid(from._internal_featureid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetFeatureRequest::CopyFrom(const GetFeatureRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:szdiagnostic.GetFeatureRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GetFeatureRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GetFeatureRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GetFeatureRequest::InternalSwap(GetFeatureRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.featureid_, other->_impl_.featureid_);
}

::google::protobuf::Metadata GetFeatureRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_szdiagnostic_2eproto_getter, &descriptor_table_szdiagnostic_2eproto_once,
      file_level_metadata_szdiagnostic_2eproto[4]);
}
// ===================================================================

class GetFeatureResponse::_Internal {
 public:
};

GetFeatureResponse::GetFeatureResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:szdiagnostic.GetFeatureResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetFeatureResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : result_(arena, from.result_),
        _cached_size_{0} {}

GetFeatureResponse::GetFeatureResponse(
    ::google::protobuf::Arena* arena,
    const GetFeatureResponse& from)
    : ::google::protobuf::Message(arena) {
  GetFeatureResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:szdiagnostic.GetFeatureResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetFeatureResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : result_(arena),
        _cached_size_{0} {}

inline void GetFeatureResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetFeatureResponse::~GetFeatureResponse() {
  // @@protoc_insertion_point(destructor:szdiagnostic.GetFeatureResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetFeatureResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.result_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GetFeatureResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:szdiagnostic.GetFeatureResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GetFeatureResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 46, 2> GetFeatureResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetFeatureResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string result = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetFeatureResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string result = 1;
    {PROTOBUF_FIELD_OFFSET(GetFeatureResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\37\6\0\0\0\0\0\0"
    "szdiagnostic.GetFeatureResponse"
    "result"
  }},
};

::uint8_t* GetFeatureResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:szdiagnostic.GetFeatureResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string result = 1;
  if (!this->_internal_result().empty()) {
    const std::string& _s = this->_internal_result();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "szdiagnostic.GetFeatureResponse.result");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:szdiagnostic.GetFeatureResponse)
  return target;
}

::size_t GetFeatureResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:szdiagnostic.GetFeatureResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string result = 1;
  if (!this->_internal_result().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GetFeatureResponse::_class_data_ = {
    GetFeatureResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GetFeatureResponse::GetClassData() const {
  return &_class_data_;
}

void GetFeatureResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GetFeatureResponse*>(&to_msg);
  auto& from = static_cast<const GetFeatureResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:szdiagnostic.GetFeatureResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_result().empty()) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetFeatureResponse::CopyFrom(const GetFeatureResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:szdiagnostic.GetFeatureResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GetFeatureResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GetFeatureResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GetFeatureResponse::InternalSwap(GetFeatureResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.result_, &other->_impl_.result_, arena);
}

::google::protobuf::Metadata GetFeatureResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_szdiagnostic_2eproto_getter, &descriptor_table_szdiagnostic_2eproto_once,
      file_level_metadata_szdiagnostic_2eproto[5]);
}
// ===================================================================

class PurgeRepositoryRequest::_Internal {
 public:
};

PurgeRepositoryRequest::PurgeRepositoryRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:szdiagnostic.PurgeRepositoryRequest)
}
PurgeRepositoryRequest::PurgeRepositoryRequest(
    ::google::protobuf::Arena* arena,
    const PurgeRepositoryRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  PurgeRepositoryRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:szdiagnostic.PurgeRepositoryRequest)
}









::google::protobuf::Metadata PurgeRepositoryRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_szdiagnostic_2eproto_getter, &descriptor_table_szdiagnostic_2eproto_once,
      file_level_metadata_szdiagnostic_2eproto[6]);
}
// ===================================================================

class PurgeRepositoryResponse::_Internal {
 public:
};

PurgeRepositoryResponse::PurgeRepositoryResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:szdiagnostic.PurgeRepositoryResponse)
}
PurgeRepositoryResponse::PurgeRepositoryResponse(
    ::google::protobuf::Arena* arena,
    const PurgeRepositoryResponse& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  PurgeRepositoryResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:szdiagnostic.PurgeRepositoryResponse)
}









::google::protobuf::Metadata PurgeRepositoryResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_szdiagnostic_2eproto_getter, &descriptor_table_szdiagnostic_2eproto_once,
      file_level_metadata_szdiagnostic_2eproto[7]);
}
// ===================================================================

class ReinitializeRequest::_Internal {
 public:
};

ReinitializeRequest::ReinitializeRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:szdiagnostic.ReinitializeRequest)
}
ReinitializeRequest::ReinitializeRequest(
    ::google::protobuf::Arena* arena, const ReinitializeRequest& from)
    : ReinitializeRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ReinitializeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ReinitializeRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.configid_ = {};
}
ReinitializeRequest::~ReinitializeRequest() {
  // @@protoc_insertion_point(destructor:szdiagnostic.ReinitializeRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ReinitializeRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ReinitializeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:szdiagnostic.ReinitializeRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.configid_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ReinitializeRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ReinitializeRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ReinitializeRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 configId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ReinitializeRequest, _impl_.configid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ReinitializeRequest, _impl_.configid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 configId = 1;
    {PROTOBUF_FIELD_OFFSET(ReinitializeRequest, _impl_.configid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ReinitializeRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:szdiagnostic.ReinitializeRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 configId = 1;
  if (this->_internal_configid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_configid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:szdiagnostic.ReinitializeRequest)
  return target;
}

::size_t ReinitializeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:szdiagnostic.ReinitializeRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 configId = 1;
  if (this->_internal_configid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_configid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ReinitializeRequest::_class_data_ = {
    ReinitializeRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ReinitializeRequest::GetClassData() const {
  return &_class_data_;
}

void ReinitializeRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ReinitializeRequest*>(&to_msg);
  auto& from = static_cast<const ReinitializeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:szdiagnostic.ReinitializeRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_configid() != 0) {
    _this->_internal_set_configid(from._internal_configid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReinitializeRequest::CopyFrom(const ReinitializeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:szdiagnostic.ReinitializeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ReinitializeRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ReinitializeRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ReinitializeRequest::InternalSwap(ReinitializeRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.configid_, other->_impl_.configid_);
}

::google::protobuf::Metadata ReinitializeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_szdiagnostic_2eproto_getter, &descriptor_table_szdiagnostic_2eproto_once,
      file_level_metadata_szdiagnostic_2eproto[8]);
}
// ===================================================================

class ReinitializeResponse::_Internal {
 public:
};

ReinitializeResponse::ReinitializeResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:szdiagnostic.ReinitializeResponse)
}
ReinitializeResponse::ReinitializeResponse(
    ::google::protobuf::Arena* arena,
    const ReinitializeResponse& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  ReinitializeResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:szdiagnostic.ReinitializeResponse)
}









::google::protobuf::Metadata ReinitializeResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_szdiagnostic_2eproto_getter, &descriptor_table_szdiagnostic_2eproto_once,
      file_level_metadata_szdiagnostic_2eproto[9]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace szdiagnostic
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
