# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: g2configmgr.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("g2configmgr.proto", :syntax => :proto3) do
    add_message "g2configmgr.AddConfigRequest" do
      optional :configStr, :string, 1
      optional :configComments, :string, 2
    end
    add_message "g2configmgr.AddConfigResponse" do
      optional :result, :int64, 1
    end
    add_message "g2configmgr.DestroyRequest" do
    end
    add_message "g2configmgr.DestroyResponse" do
    end
    add_message "g2configmgr.GetConfigRequest" do
      optional :configID, :int64, 1
    end
    add_message "g2configmgr.GetConfigResponse" do
      optional :result, :string, 1
    end
    add_message "g2configmgr.GetConfigListRequest" do
    end
    add_message "g2configmgr.GetConfigListResponse" do
      optional :result, :string, 1
    end
    add_message "g2configmgr.GetDefaultConfigIDRequest" do
    end
    add_message "g2configmgr.GetDefaultConfigIDResponse" do
      optional :configID, :int64, 1
    end
    add_message "g2configmgr.InitRequest" do
      optional :moduleName, :string, 1
      optional :iniParams, :string, 2
      optional :verboseLogging, :int64, 3
    end
    add_message "g2configmgr.InitResponse" do
    end
    add_message "g2configmgr.ReplaceDefaultConfigIDRequest" do
      optional :oldConfigID, :int64, 1
      optional :newConfigID, :int64, 2
    end
    add_message "g2configmgr.ReplaceDefaultConfigIDResponse" do
    end
    add_message "g2configmgr.SetDefaultConfigIDRequest" do
      optional :configID, :int64, 1
    end
    add_message "g2configmgr.SetDefaultConfigIDResponse" do
    end
  end
end

module G2configmgr
  AddConfigRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.AddConfigRequest").msgclass
  AddConfigResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.AddConfigResponse").msgclass
  DestroyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.DestroyRequest").msgclass
  DestroyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.DestroyResponse").msgclass
  GetConfigRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.GetConfigRequest").msgclass
  GetConfigResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.GetConfigResponse").msgclass
  GetConfigListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.GetConfigListRequest").msgclass
  GetConfigListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.GetConfigListResponse").msgclass
  GetDefaultConfigIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.GetDefaultConfigIDRequest").msgclass
  GetDefaultConfigIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.GetDefaultConfigIDResponse").msgclass
  InitRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.InitRequest").msgclass
  InitResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.InitResponse").msgclass
  ReplaceDefaultConfigIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.ReplaceDefaultConfigIDRequest").msgclass
  ReplaceDefaultConfigIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.ReplaceDefaultConfigIDResponse").msgclass
  SetDefaultConfigIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.SetDefaultConfigIDRequest").msgclass
  SetDefaultConfigIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g2configmgr.SetDefaultConfigIDResponse").msgclass
end
