<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: szengine.proto

namespace Szengine;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>szengine.FindInterestingEntitiesByEntityIdRequest</code>
 */
class FindInterestingEntitiesByEntityIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 entityId = 1;</code>
     */
    protected $entityId = 0;
    /**
     * Generated from protobuf field <code>int64 flags = 2;</code>
     */
    protected $flags = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $entityId
     *     @type int|string $flags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Szengine::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 entityId = 1;</code>
     * @return int|string
     */
    public function getEntityId()
    {
        return $this->entityId;
    }

    /**
     * Generated from protobuf field <code>int64 entityId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEntityId($var)
    {
        GPBUtil::checkInt64($var);
        $this->entityId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 flags = 2;</code>
     * @return int|string
     */
    public function getFlags()
    {
        return $this->flags;
    }

    /**
     * Generated from protobuf field <code>int64 flags = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFlags($var)
    {
        GPBUtil::checkInt64($var);
        $this->flags = $var;

        return $this;
    }

}

