<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: szengine.proto

namespace Szengine;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>szengine.FindNetworkByEntityIdRequest</code>
 */
class FindNetworkByEntityIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string entityIds = 1;</code>
     */
    protected $entityIds = '';
    /**
     * Generated from protobuf field <code>int64 maxDegrees = 2;</code>
     */
    protected $maxDegrees = 0;
    /**
     * Generated from protobuf field <code>int64 buildOutDegree = 3;</code>
     */
    protected $buildOutDegree = 0;
    /**
     * Generated from protobuf field <code>int64 buildOutMaxEntities = 4;</code>
     */
    protected $buildOutMaxEntities = 0;
    /**
     * Generated from protobuf field <code>int64 flags = 5;</code>
     */
    protected $flags = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $entityIds
     *     @type int|string $maxDegrees
     *     @type int|string $buildOutDegree
     *     @type int|string $buildOutMaxEntities
     *     @type int|string $flags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Szengine::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string entityIds = 1;</code>
     * @return string
     */
    public function getEntityIds()
    {
        return $this->entityIds;
    }

    /**
     * Generated from protobuf field <code>string entityIds = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->entityIds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 maxDegrees = 2;</code>
     * @return int|string
     */
    public function getMaxDegrees()
    {
        return $this->maxDegrees;
    }

    /**
     * Generated from protobuf field <code>int64 maxDegrees = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxDegrees($var)
    {
        GPBUtil::checkInt64($var);
        $this->maxDegrees = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 buildOutDegree = 3;</code>
     * @return int|string
     */
    public function getBuildOutDegree()
    {
        return $this->buildOutDegree;
    }

    /**
     * Generated from protobuf field <code>int64 buildOutDegree = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBuildOutDegree($var)
    {
        GPBUtil::checkInt64($var);
        $this->buildOutDegree = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 buildOutMaxEntities = 4;</code>
     * @return int|string
     */
    public function getBuildOutMaxEntities()
    {
        return $this->buildOutMaxEntities;
    }

    /**
     * Generated from protobuf field <code>int64 buildOutMaxEntities = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBuildOutMaxEntities($var)
    {
        GPBUtil::checkInt64($var);
        $this->buildOutMaxEntities = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 flags = 5;</code>
     * @return int|string
     */
    public function getFlags()
    {
        return $this->flags;
    }

    /**
     * Generated from protobuf field <code>int64 flags = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFlags($var)
    {
        GPBUtil::checkInt64($var);
        $this->flags = $var;

        return $this;
    }

}

