// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: g2config.proto

package com.senzing.g2.engine.grpc.G2Config;

public interface ClearLastExceptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:g2config.ClearLastExceptionResponse)
    com.google.protobuf.MessageOrBuilder {
}
