// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: g2engine.proto

package com.senzing.g2.engine.grpc.G2Engine;

public interface ExportConfigAndConfigIDResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:g2engine.ExportConfigAndConfigIDResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string config = 1;</code>
   * @return The config.
   */
  java.lang.String getConfig();
  /**
   * <code>string config = 1;</code>
   * @return The bytes for config.
   */
  com.google.protobuf.ByteString
      getConfigBytes();

  /**
   * <code>int64 configID = 2;</code>
   * @return The configID.
   */
  long getConfigID();
}
