// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: g2engine.proto

package com.senzing.g2.engine.grpc.G2Engine;

public interface GetActiveConfigIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:g2engine.GetActiveConfigIDRequest)
    com.google.protobuf.MessageOrBuilder {
}
