// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: g2engine.proto

package com.senzing.g2.engine.grpc.G2Engine;

public interface GetRedoRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:g2engine.GetRedoRecordRequest)
    com.google.protobuf.MessageOrBuilder {
}
