// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: g2engine.proto

package com.senzing.g2.engine.grpc.G2Engine;

public interface GetVirtualEntityByRecordIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:g2engine.GetVirtualEntityByRecordIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recordList = 1;</code>
   * @return The recordList.
   */
  java.lang.String getRecordList();
  /**
   * <code>string recordList = 1;</code>
   * @return The bytes for recordList.
   */
  com.google.protobuf.ByteString
      getRecordListBytes();
}
